service: ton-user
frameworkVersion: '2'

custom:
  settings:
    USERS_TABLE: users

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDB:DescribeTable
        - dynamoDB:Scan
        - dynamoDB:GetItem
        - dynamoDB:PutItem
        - dynamoDB:UpdateItem
        - dynamoDB:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.USERS_TABLE}"


  lambdaHashingVersion: 20201221

functions:
  createUser:
    handler: handler.hello
    events:
    - http:
      path: /user
      method: post

resource:
  Resource:
    UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "id"
      - AttributeType: "S"
      KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1 
      TableName: ${self.custom.settings.USERS_TABLE}