service: ton-user
frameworkVersion: '2'

custom:
    tableName: users-tables

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2

functions:
  user:
    handler: lambdas/user.handler
    events:
      - http:
          path: user/{ID}
          method: GET
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
            - AttributeName: ID
              KeyType: HASH
        BillingMode: PAY_PER_REQUEST
              