service: ton-user
frameworkVersion: '2'

custom:
    tableName: users-table

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  user:
    handler: lambdas/endpoints/user.handler
    events:
      - http:
          path: user/{ID}
          method: GET
          cors: true
  accessCounter:
    handler: lambdas/endpoints/accessCounter.handler
    events:
      - http:
          path: counter
          method: PUT
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
            - AttributeName: ID
              KeyType: HASH
        BillingMode: PAY_PER_REQUEST
              